/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.MyGradleApp;
import java.time.LocalDateTime;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    
    // pluralizer method
    
    public String pluralizer(String word , int num){
       
        if(num==1)
            return "I own"+num +" "+ word;
        else if(num ==0 || num >1) 
            return "I own"+num +" "+ word+ "s";
        else 
            return "Invalid Number";
    }
    
    
    // flipNHead method 
    
    public String flipNHead(int num){
    
            int headCounter,counter;
            headCounter=counter=0;
            do{
                 double randomNum=Math.random();
                 if(randomNum >0.5)
                 {
                    headCounter++;
                     System.out.println("Head");
                 }
                 else 
                     System.out.println("Tail");
            counter++;
            
            } while(headCounter!=num);
            
            return "It took "+counter+" filps to get "+num+" heads.";
    }
    
    
    // clock method 
    
    public static void clock(){
    
         while (true){
               
             LocalDateTime obj=LocalDateTime.now();
             System.out.println(obj.getHour() +": "+obj.getMinute()+": "+ obj.getSecond());
             
             try{
                  Thread.sleep(1000);
             
             }catch (InterruptedException ex){
                   System.out.println("Error");
             }
         
         
         
         }
         

    
    }
    
             // reverse method
    public static void reverse(){
       
        Scanner input=new Scanner(System.in);
        System.out.print("Please enter the size of the Array: ");
        int size=input.nextInt();
        int x[]=new int[size];
        
       for(int j=0; j<x.length;j++){
           
           System.out.print("Enter element #"+(j+1)+" : ");
           x[j]=input.nextInt();
}
       int start=0;
       for(int end=x.length-1; start<end;start++,end--)
        { 
            int temp=x[start];
            x[start]=x[end];
            x[end]=temp;
            
            
       //System.out.println(x[start]);
        }
   for(int i=0; i<x.length ;i++ ){
       
        System.out.println(x[i]);
   }
   
       
   
   }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        App obj=new App();
        // print the pluralizer method 
        System.out.println(obj.pluralizer("book", 5));
        
        // print filpNHead method 
        System.out.println(obj.flipNHead(5));
        
        //clock method applying 
        //clock();
        
        reverse();
        
        
    }
}
